const artists = [
  'Kendrick Lamar',
  'Taylor Swift',
  'Drake',
  'Billie Eilish',
  'The Weeknd',
  'Dua Lipa',
  'Harry Styles',
  'Ed Sheeran',
  'Rihanna',
  'Post Malone',
  'Lady Gaga',
  'Justin Bieber',
  'Bruno Mars',
  'Eminem',
  'Adele',
  'Maroon 5',
  'Imagine Dragons',
  'BTS',
  'Ariana Grande',
  'Coldplay',
  'Kanye West',
  'Beyoncé',
  'Jay-Z',
  'Doja Cat',
  'Olivia Rodrigo',
  'Bad Bunny',
  'SZA',
  'The Chainsmokers',
  'Twenty One Pilots',
  'Imagine Dragons',
  'Calvin Harris',
  'Marshmello',
  'David Guetta',
  'The Black Eyed Peas',
  'Katy Perry',
  'Nicki Minaj',
  'Prince',
  'Michael Jackson',
  'Madonna',
  'Whitney Houston',
  "Guns N' Roses",
  'Bon Jovi',
  'Bruce Springsteen',
  'U2',
  'Metallica',
  'R.E.M.',
  'The Cure',
  'Depeche Mode',
  'New Order',
  'The Smiths',
  'David Bowie',
  'The Police',
  'Phil Collins',
  'Genesis',
  'Tears for Fears',
  'INXS',
  'A-ha',
  'Duran Duran',
  'Wham!',
  'Spandau Ballet',
  'Culture Club',
  'The Eurythmics',
  'Simple Minds',
  'Pet Shop Boys',
  'The Smiths',
  'The Cure',
  'New Order',
  'Joy Division',
  'The Smiths',
  'The Cure',
  'New Order',
  'Joy Division',
  'The Smiths',
  'The Cure',
  'New Order',
  'Joy Division',
  'The Smiths',
  'The Cure',
  'New Order',
  'Joy Division',
  'The Smiths',
  'The Cure',
  'New Order',
  'Joy Division',
  'The Smiths',
  'The Cure',
  'New Order',
  'Joy Division',
  'The Smiths',
  'The Cure',
  'New Order',
  'Joy Division',
  'David Bowie',
  'Queen',
  'Led Zeppelin',
  'Pink Floyd',
  'The Rolling Stones',
  'The Who',
  'Elton John',
  'The Eagles',
  'Fleetwood Mac',
  'ABBA',
  'Bee Gees',
  'The Kinks',
  'The Police',
  'Supertramp',
  'Kiss',
  'Aerosmith',
  'Black Sabbath',
  'Deep Purple',
  'Jimi Hendrix',
  'The Doors',
  'The Beach Boys',
  'Steely Dan',
  'Electric Light Orchestra',
  'Yes',
  'Genesis',
  'King Crimson',
  'Emerson, Lake & Palmer',
  'The Allman Brothers Band',
  'Lynyrd Skynyrd',
  'The Grateful Dead',
  'The Band',
  'Crosby, Stills, Nash & Young',
  'The Doobie Brothers',
  'The Beatles',
  'The Rolling Stones',
  'Bob Dylan',
  'The Jimi Hendrix Experience',
  'The Doors',
  'The Who',
  'The Beach Boys',
  'The Kinks',
  'David Bowie',
  'The Velvet Underground',
  'The Grateful Dead',
  'Creedence Clearwater Revival',
  'Janis Joplin',
  'Jimi Hendrix',
  'The Doors',
  'The Who',
  'The Beach Boys',
  'The Kinks',
  'David Bowie',
  'The Velvet Underground',
  'The Grateful Dead',
  'Creedence Clearwater Revival',
  'Janis Joplin',
  'Jimi Hendrix',
  'The Doors',
  'The Who',
  'The Beach Boys',
  'The Kinks',
  'David Bowie',
  'The Velvet Underground',
  'The Grateful Dead',
  'Creedence Clearwater Revival',
  'Janis Joplin'
]

export default artists
